version: 2
# Build documentation in the docs/ directory with Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - htmlzip
  
python:
  install:
    - requirements: requirements.txt
git:
  depth: 10